# CMake generated Testfile for 
# Source directory: /home/wanghongyu/pexsi/superlu_dist/EXAMPLE
# Build directory: /home/wanghongyu/pexsi/superlu_dist/build_cpu/EXAMPLE
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(pddrive1 "/usr/local/spack/opt/spack/linux-centos7-skylake_avx512/gcc-7.5.0/openmpi-4.1.4-p5kkl6mf5ozduge4ete4hue3qtsiglli/bin/mpiexec" "-n" "4" "/home/wanghongyu/pexsi/superlu_dist/build_cpu/EXAMPLE/pddrive1" "-r" "2" "-c" "2" "/home/wanghongyu/pexsi/superlu_dist/EXAMPLE/big.rua")
set_tests_properties(pddrive1 PROPERTIES  _BACKTRACE_TRIPLES "/home/wanghongyu/pexsi/superlu_dist/EXAMPLE/CMakeLists.txt;20;add_test;/home/wanghongyu/pexsi/superlu_dist/EXAMPLE/CMakeLists.txt;45;add_superlu_dist_example;/home/wanghongyu/pexsi/superlu_dist/EXAMPLE/CMakeLists.txt;0;")
add_test(pddrive2 "/usr/local/spack/opt/spack/linux-centos7-skylake_avx512/gcc-7.5.0/openmpi-4.1.4-p5kkl6mf5ozduge4ete4hue3qtsiglli/bin/mpiexec" "-n" "4" "/home/wanghongyu/pexsi/superlu_dist/build_cpu/EXAMPLE/pddrive2" "-r" "2" "-c" "2" "/home/wanghongyu/pexsi/superlu_dist/EXAMPLE/big.rua")
set_tests_properties(pddrive2 PROPERTIES  _BACKTRACE_TRIPLES "/home/wanghongyu/pexsi/superlu_dist/EXAMPLE/CMakeLists.txt;20;add_test;/home/wanghongyu/pexsi/superlu_dist/EXAMPLE/CMakeLists.txt;51;add_superlu_dist_example;/home/wanghongyu/pexsi/superlu_dist/EXAMPLE/CMakeLists.txt;0;")
add_test(pddrive3 "/usr/local/spack/opt/spack/linux-centos7-skylake_avx512/gcc-7.5.0/openmpi-4.1.4-p5kkl6mf5ozduge4ete4hue3qtsiglli/bin/mpiexec" "-n" "4" "/home/wanghongyu/pexsi/superlu_dist/build_cpu/EXAMPLE/pddrive3" "-r" "2" "-c" "2" "/home/wanghongyu/pexsi/superlu_dist/EXAMPLE/big.rua")
set_tests_properties(pddrive3 PROPERTIES  _BACKTRACE_TRIPLES "/home/wanghongyu/pexsi/superlu_dist/EXAMPLE/CMakeLists.txt;20;add_test;/home/wanghongyu/pexsi/superlu_dist/EXAMPLE/CMakeLists.txt;57;add_superlu_dist_example;/home/wanghongyu/pexsi/superlu_dist/EXAMPLE/CMakeLists.txt;0;")
add_test(pzdrive1 "/usr/local/spack/opt/spack/linux-centos7-skylake_avx512/gcc-7.5.0/openmpi-4.1.4-p5kkl6mf5ozduge4ete4hue3qtsiglli/bin/mpiexec" "-n" "4" "/home/wanghongyu/pexsi/superlu_dist/build_cpu/EXAMPLE/pzdrive1" "-r" "2" "-c" "2" "/home/wanghongyu/pexsi/superlu_dist/EXAMPLE/cg20.cua")
set_tests_properties(pzdrive1 PROPERTIES  _BACKTRACE_TRIPLES "/home/wanghongyu/pexsi/superlu_dist/EXAMPLE/CMakeLists.txt;20;add_test;/home/wanghongyu/pexsi/superlu_dist/EXAMPLE/CMakeLists.txt;180;add_superlu_dist_example;/home/wanghongyu/pexsi/superlu_dist/EXAMPLE/CMakeLists.txt;0;")
add_test(pzdrive2 "/usr/local/spack/opt/spack/linux-centos7-skylake_avx512/gcc-7.5.0/openmpi-4.1.4-p5kkl6mf5ozduge4ete4hue3qtsiglli/bin/mpiexec" "-n" "4" "/home/wanghongyu/pexsi/superlu_dist/build_cpu/EXAMPLE/pzdrive2" "-r" "2" "-c" "2" "/home/wanghongyu/pexsi/superlu_dist/EXAMPLE/cg20.cua")
set_tests_properties(pzdrive2 PROPERTIES  _BACKTRACE_TRIPLES "/home/wanghongyu/pexsi/superlu_dist/EXAMPLE/CMakeLists.txt;20;add_test;/home/wanghongyu/pexsi/superlu_dist/EXAMPLE/CMakeLists.txt;186;add_superlu_dist_example;/home/wanghongyu/pexsi/superlu_dist/EXAMPLE/CMakeLists.txt;0;")
add_test(pzdrive3 "/usr/local/spack/opt/spack/linux-centos7-skylake_avx512/gcc-7.5.0/openmpi-4.1.4-p5kkl6mf5ozduge4ete4hue3qtsiglli/bin/mpiexec" "-n" "4" "/home/wanghongyu/pexsi/superlu_dist/build_cpu/EXAMPLE/pzdrive3" "-r" "2" "-c" "2" "/home/wanghongyu/pexsi/superlu_dist/EXAMPLE/cg20.cua")
set_tests_properties(pzdrive3 PROPERTIES  _BACKTRACE_TRIPLES "/home/wanghongyu/pexsi/superlu_dist/EXAMPLE/CMakeLists.txt;20;add_test;/home/wanghongyu/pexsi/superlu_dist/EXAMPLE/CMakeLists.txt;192;add_superlu_dist_example;/home/wanghongyu/pexsi/superlu_dist/EXAMPLE/CMakeLists.txt;0;")
